### PR TITLE
Support building for iOS and tvOS

### PR DESCRIPTION
**Pull request by yoshisuga**
Had to disable dynarec as it causes the core to crash when executing content.

### CODE REVIEW

**Comment by schellingb** [comment]
Hi there, thanks for the PR.
Do you have any idea what causes issues with dynarec? It works fine on the Android Arm64 builds which should be somewhat similar?

**Comment by yoshisuga** [comment]
Yes, dynarec isn’t supported (easily) on jailbroken iOS devices. It’s not
allowed at the OS level for security reasons. All the cores built for
RetroArch on iOS do not have jailbreak as a prerequisite.

**Comment by yoshisuga** [comment]
The interpreted core runs nicely in iOS and tvOS. Thanks!

**Comment by schellingb** [comment]
Merged via #135

**Pull request closed without merging**
