### PR TITLE
Bugfix/mips32 dynarec

### PR DESCRIPTION
**Pull request by john-parton**
This is supposed to fix dynarec on the mip32/RG350 platform. https://github.com/schellingb/dosbox-pure/issues/104

Doesn't work yet.

### CODE REVIEW

**Comment by john-parton** [comment]
I should pick this up again.

**Comment by john-parton** [comment]
More info: https://www.vogons.org/viewtopic.php?t=34939
https://github.com/dmitrysmagin/dosbox-gcw0

**Comment by schellingb** [comment]
Is this still relevant?

**Comment by john-parton** [comment]
I've got no clue. I barely remember what I coded last month versus 16 months ago.

**Pull request closed without merging**
